Fix for dealing with foreign key constraints, need to address hard coded unique keys in test procedures

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,16 +1,44 @@
 #!/bin/bash 
+
 # Installation script for sqlSec
 # Jason Gerfen <jason.gerfen@gmail.com>
 
 e="echo -en"
-ver="v0.1"
+ver="v0.2.0"
 txt_green='\e[1;32m'
 txt_reset='\e[0m'
 
-${e} "${txt_green}sqlSec${txt_reset}\n"
-echo "A symmetric encryption key / data rotation tool for MySQL"
-echo ""
+# Show usage menu
+usage()
+{
+  cat << EOF
+sqlSec - A symmetric encryption / data rotation tool for MySQL
 
+Usage: $0 [options]
+
+OPTIONS:
+   -h      Show this message
+   -t      Install test database & perform automated test suite
+
+EOF
+}
+
+# Tests disabled by default
+test=0
+
+# Parse and apply specified arugments
+while getopts “ht” OPTION ; do
+  case $OPTION in
+    h)
+      usage && exit 1 ;;
+    t)
+      test=1 ;;
+    ?)
+      usage && exit 1 ;;
+  esac
+done
+
+# Y/N prompt function
 function ask {
  while true; do
   if [ "${2:-}" = "Y" ]; then
@@ -61,7 +89,7 @@ read -p "Database server name [localhost]: " server
 sed -i "s/{SERVER}/${server:=localhost}/g" .install/*.sql
 
 # Setup test env if asked
-if [ "${1}" == "test" ] ; then
+if [ "${test}" == 1 ] ; then
   cp -fr tests/test-database.sql .install/
 
   # User defined database settings
@@ -92,7 +120,16 @@ if [ "${1}" == "test" ] ; then
   sed -i "s/{RO_PW}/${ro_pass:=${tup}}/g" .install/*.sql
   echo ""
 
-  echo "Installing test database..."
+  echo ""
+  ${e} "${txt_green}Test database account info${txt_reset}\n"
+
+  echo "  Test database server: ${server}"
+  echo "  Test database name: ${name}"
+  echo "  Test database read-write account: ${admin}"
+  echo "  Test database read-write password: ${admin_pass}"
+  echo "  Test database read-only account: ${ro}"
+  echo "  Test database read-only password: ${ro_pass}"
+
   mysql -u ${mu} --password=${pass} < .install/test-database.sql
   echo ""
 fi
@@ -149,32 +186,38 @@ cleanup(){
  exit
 }
 
-tables(){
+fields(){
  table="${1}"
  PS3="Select field to enable encryption: "
- fields=$(mysql -u ${mu} --password=${pass} ${name} -sss -e "describe ${table}" | awk '{ print $1 }')
- fields+=" Main"
- select field in ${fields}; do
+ tables=$(mysql -u ${mu} --password=${pass} ${name} -sss -e "describe ${table}" | awk '{ print $1 }')
+ tables+=" Main"
+ select field in ${tables}; do
   case ${field} in
    "Main")
-    fields
+    tables
     break
     ;;
    *)
     if [ -n "${field}" ]; then
-     mysql -u ${mu} --password=${pass} ${name} -sss -e 'ALTER TABLE `'${table}'` MODIFY `'${field}'` BLOB'
-     mysql -u ${mu} --password=${pass} ${name} -sss -e 'INSERT INTO `sqlSec_map` (`tbl`, `field`) VALUES ("'${table}'", "'${field}'")'
-     tables ${table}
+     # Make sure there aren't any foreign keys on the field selected or we won't be able to convert the field to a BLOB column type
+     chk=$(mysql -u ${mu} --password=${pass} ${name} -sss -e 'select count(*) AS total from information_schema.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = "'${name}'" AND TABLE_NAME = "'${table}'" AND COLUMN_NAME = "'${field}'";')
+     if [ "${chk}" -gt 0 ] ; then
+       echo "A foreign key constraint exists for this field. Cannot use '${table}.${field}'"
+     else
+       mysql -u ${mu} --password=${pass} ${name} -sss -e 'ALTER TABLE `'${table}'` MODIFY `'${field}'` BLOB'
+       mysql -u ${mu} --password=${pass} ${name} -sss -e 'INSERT INTO `sqlSec_map` (`tbl`, `field`) VALUES ("'${table}'", "'${field}'")'
+     fi
+     fields ${table}
     else
      echo "Invalid choice"
-     tables ${table}
+     fields ${table}
     fi
     ;;
   esac
  done
 }
 
-fields(){
+tables(){
  PS3="Select table to view fields: "
  tables=$(mysql -u ${mu} --password=${pass} ${name} -sss -e "show tables" | awk '{ print $1 }')
  tables+=" Quit"
@@ -185,14 +228,14 @@ fields(){
     ;;
    *)
     if [ -n "${table}" ]; then
-     tables ${table}
+     fields ${table}
     else
      echo "Invalid choice"
-     tables ${table}
+     fields ${table}
     fi
     ;;
   esac
  done
 }
 
-fields
+tables
